// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2GCEmsPibNOwzmRELrM7S9WfS0kc-ztA',
    appId: '1:830191242892:web:0fb264aee40f90294d35a9',
    messagingSenderId: '830191242892',
    projectId: 'staff-crud-app-ac421',
    authDomain: 'staff-crud-app-ac421.firebaseapp.com',
    storageBucket: 'staff-crud-app-ac421.firebasestorage.app',
    measurementId: 'G-MWFDT58G9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD8Uc6oF4RLdByo_DTPHH-CticlWe0JvE',
    appId: '1:830191242892:android:7ec51b8165c4e6524d35a9',
    messagingSenderId: '830191242892',
    projectId: 'staff-crud-app-ac421',
    storageBucket: 'staff-crud-app-ac421.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlLJHuxpDwTlJIunDWPjCaCqhBoJKHV4g',
    appId: '1:830191242892:ios:654e4dcc31f338704d35a9',
    messagingSenderId: '830191242892',
    projectId: 'staff-crud-app-ac421',
    storageBucket: 'staff-crud-app-ac421.firebasestorage.app',
    iosBundleId: 'com.example.staffCrudApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlLJHuxpDwTlJIunDWPjCaCqhBoJKHV4g',
    appId: '1:830191242892:ios:654e4dcc31f338704d35a9',
    messagingSenderId: '830191242892',
    projectId: 'staff-crud-app-ac421',
    storageBucket: 'staff-crud-app-ac421.firebasestorage.app',
    iosBundleId: 'com.example.staffCrudApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2GCEmsPibNOwzmRELrM7S9WfS0kc-ztA',
    appId: '1:830191242892:web:91be1a8490776a7a4d35a9',
    messagingSenderId: '830191242892',
    projectId: 'staff-crud-app-ac421',
    authDomain: 'staff-crud-app-ac421.firebaseapp.com',
    storageBucket: 'staff-crud-app-ac421.firebasestorage.app',
    measurementId: 'G-LWJNC6QVHE',
  );
}
